server:
  port: 8000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: nuochong-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/nuochong2017/NuochongConfigServer
          search-paths: config-repo
          username: insanetomato@me.com
          password: dearhw0603
    bus:
      enabled: true
      trace:
        enabled: true
management:
  endpoints:
    web:
      exposure:
        include: "*"